#include "Logical\Gotoxy.cpp"
#include "Logical\Textcolor.cpp"
#include "Logical\PollingCycle.cpp"
#include "Drawing\CommandHelper.cpp"
#include "Drawing\TitleClr.cpp"
#include "Drawing\DrawCanvas.cpp"
